export const jobData = [
    {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
      id: 1,
      title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
      company: "HINDCO Consulting Services",
      experience: "0 - 1 Years",
      salary: "Not Disclosed",
      type: "Full Time - Internship",
      location: "Mumbai",
      skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
      openToHire: "Fresher/Intern",
      postedAgo: "19 day(s)",
      mode: "In Office"
    },
    {
      id: 2,
      title: "Software Engineer Trainee",
      company: "TechNova",
      experience: "0 - 2 Years",
      salary: "3 - 5 LPA",
      type: "Full Time",
      location: "Bangalore",
      skills: "JavaScript, React, Node.js",
      openToHire: "Fresher",
      postedAgo: "12 day(s)",
      mode: "Hybrid"
    },
    {
      id: 3,
      title: "Business Analyst Intern",
      company: "BizWorks",
      experience: "0 - 1 Years",
      salary: "Not Disclosed",
      type: "Internship",
      location: "Delhi",
      skills: "Excel, PowerPoint, Analysis",
      openToHire: "Intern",
      postedAgo: "5 day(s)",
      mode: "Remote"
    },
    {
      id: 4,
      title: "Marketing Executive",
      company: "MarketMinds",
      experience: "0 - 1 Years",
      salary: "2 - 3 LPA",
      type: "Full Time",
      location: "Chennai",
      skills: "Marketing, Branding, Sales",
      openToHire: "Fresher",
      postedAgo: "7 day(s)",
      mode: "In Office"
    },
    {
      id: 5,
      title: "Graphic Design Intern",
      company: "CreativeHive",
      experience: "0 Years",
      salary: "Stipend",
      type: "Internship",
      location: "Pune",
      skills: "Photoshop, Illustrator, Figma",
      openToHire: "Intern",
      postedAgo: "3 day(s)",
      mode: "Remote"
    },
    {
      id: 6,
      title: "HR Assistant (Fresher)",
      company: "PeoplePro",
      experience: "0 - 1 Years",
      salary: "2 - 3 LPA",
      type: "Full Time",
      location: "Hyderabad",
      skills: "Recruitment, Communication, HRMS",
      openToHire: "Fresher",
      postedAgo: "10 day(s)",
      mode: "In Office"
    }, {
      id: 1,
      title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
      company: "HINDCO Consulting Services",
      experience: "0 - 1 Years",
      salary: "Not Disclosed",
      type: "Full Time - Internship",
      location: "Mumbai",
      skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
      openToHire: "Fresher/Intern",
      postedAgo: "19 day(s)",
      mode: "In Office"
    },
    {
      id: 2,
      title: "Software Engineer Trainee",
      company: "TechNova",
      experience: "0 - 2 Years",
      salary: "3 - 5 LPA",
      type: "Full Time",
      location: "Bangalore",
      skills: "JavaScript, React, Node.js",
      openToHire: "Fresher",
      postedAgo: "12 day(s)",
      mode: "Hybrid"
    },
    {
      id: 3,
      title: "Business Analyst Intern",
      company: "BizWorks",
      experience: "0 - 1 Years",
      salary: "Not Disclosed",
      type: "Internship",
      location: "Delhi",
      skills: "Excel, PowerPoint, Analysis",
      openToHire: "Intern",
      postedAgo: "5 day(s)",
      mode: "Remote"
    },
    {
      id: 4,
      title: "Marketing Executive",
      company: "MarketMinds",
      experience: "0 - 1 Years",
      salary: "2 - 3 LPA",
      type: "Full Time",
      location: "Chennai",
      skills: "Marketing, Branding, Sales",
      openToHire: "Fresher",
      postedAgo: "7 day(s)",
      mode: "In Office"
    },
    {
      id: 5,
      title: "Graphic Design Intern",
      company: "CreativeHive",
      experience: "0 Years",
      salary: "Stipend",
      type: "Internship",
      location: "Pune",
      skills: "Photoshop, Illustrator, Figma",
      openToHire: "Intern",
      postedAgo: "3 day(s)",
      mode: "Remote"
    },
    {
      id: 6,
      title: "HR Assistant (Fresher)",
      company: "PeoplePro",
      experience: "0 - 1 Years",
      salary: "2 - 3 LPA",
      type: "Full Time",
      location: "Hyderabad",
      skills: "Recruitment, Communication, HRMS",
      openToHire: "Fresher",
      postedAgo: "10 day(s)",
      mode: "In Office"
    }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
      id: 1,
      title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
      company: "HINDCO Consulting Services",
      experience: "0 - 1 Years",
      salary: "Not Disclosed",
      type: "Full Time - Internship",
      location: "Mumbai",
      skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
      openToHire: "Fresher/Intern",
      postedAgo: "19 day(s)",
      mode: "In Office"
    },
    {
      id: 2,
      title: "Software Engineer Trainee",
      company: "TechNova",
      experience: "0 - 2 Years",
      salary: "3 - 5 LPA",
      type: "Full Time",
      location: "Bangalore",
      skills: "JavaScript, React, Node.js",
      openToHire: "Fresher",
      postedAgo: "12 day(s)",
      mode: "Hybrid"
    },
    {
      id: 3,
      title: "Business Analyst Intern",
      company: "BizWorks",
      experience: "0 - 1 Years",
      salary: "Not Disclosed",
      type: "Internship",
      location: "Delhi",
      skills: "Excel, PowerPoint, Analysis",
      openToHire: "Intern",
      postedAgo: "5 day(s)",
      mode: "Remote"
    },
    {
      id: 4,
      title: "Marketing Executive",
      company: "MarketMinds",
      experience: "0 - 1 Years",
      salary: "2 - 3 LPA",
      type: "Full Time",
      location: "Chennai",
      skills: "Marketing, Branding, Sales",
      openToHire: "Fresher",
      postedAgo: "7 day(s)",
      mode: "In Office"
    },
    {
      id: 5,
      title: "Graphic Design Intern",
      company: "CreativeHive",
      experience: "0 Years",
      salary: "Stipend",
      type: "Internship",
      location: "Pune",
      skills: "Photoshop, Illustrator, Figma",
      openToHire: "Intern",
      postedAgo: "3 day(s)",
      mode: "Remote"
    },
    {
      id: 6,
      title: "HR Assistant (Fresher)",
      company: "PeoplePro",
      experience: "0 - 1 Years",
      salary: "2 - 3 LPA",
      type: "Full Time",
      location: "Hyderabad",
      skills: "Recruitment, Communication, HRMS",
      openToHire: "Fresher",
      postedAgo: "10 day(s)",
      mode: "In Office"
    }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      }, {
        id: 1,
        title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
        company: "HINDCO Consulting Services",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Full Time - Internship",
        location: "Mumbai",
        skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
        openToHire: "Fresher/Intern",
        postedAgo: "19 day(s)",
        mode: "In Office"
      },
      {
        id: 2,
        title: "Software Engineer Trainee",
        company: "TechNova",
        experience: "0 - 2 Years",
        salary: "3 - 5 LPA",
        type: "Full Time",
        location: "Bangalore",
        skills: "JavaScript, React, Node.js",
        openToHire: "Fresher",
        postedAgo: "12 day(s)",
        mode: "Hybrid"
      },
      {
        id: 3,
        title: "Business Analyst Intern",
        company: "BizWorks",
        experience: "0 - 1 Years",
        salary: "Not Disclosed",
        type: "Internship",
        location: "Delhi",
        skills: "Excel, PowerPoint, Analysis",
        openToHire: "Intern",
        postedAgo: "5 day(s)",
        mode: "Remote"
      },
      {
        id: 4,
        title: "Marketing Executive",
        company: "MarketMinds",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Chennai",
        skills: "Marketing, Branding, Sales",
        openToHire: "Fresher",
        postedAgo: "7 day(s)",
        mode: "In Office"
      },
      {
        id: 5,
        title: "Graphic Design Intern",
        company: "CreativeHive",
        experience: "0 Years",
        salary: "Stipend",
        type: "Internship",
        location: "Pune",
        skills: "Photoshop, Illustrator, Figma",
        openToHire: "Intern",
        postedAgo: "3 day(s)",
        mode: "Remote"
      },
      {
        id: 6,
        title: "HR Assistant (Fresher)",
        company: "PeoplePro",
        experience: "0 - 1 Years",
        salary: "2 - 3 LPA",
        type: "Full Time",
        location: "Hyderabad",
        skills: "Recruitment, Communication, HRMS",
        openToHire: "Fresher",
        postedAgo: "10 day(s)",
        mode: "In Office"
      },
    {
      id: 1,
      title: "MBA FRESHER | MARKETING / BRAND MANAGEMENT",
      company: "HINDCO Consulting Services",
      experience: "0 - 1 Years",
      salary: "Not Disclosed",
      type: "Full Time - Internship",
      location: "Mumbai",
      skills: "Executive Search, Marketing, Mba, Branding, Management Trainee, Brand Management, Intern",
      openToHire: "Fresher/Intern",
      postedAgo: "19 day(s)",
      mode: "In Office"
    },
    {
      id: 2,
      title: "Software Engineer Trainee",
      company: "TechNova",
      experience: "0 - 2 Years",
      salary: "3 - 5 LPA",
      type: "Full Time",
      location: "Bangalore",
      skills: "JavaScript, React, Node.js",
      openToHire: "Fresher",
      postedAgo: "12 day(s)",
      mode: "Hybrid"
    },
    {
      id: 3,
      title: "Business Analyst Intern",
      company: "BizWorks",
      experience: "0 - 1 Years",
      salary: "Not Disclosed",
      type: "Internship",
      location: "Delhi",
      skills: "Excel, PowerPoint, Analysis",
      openToHire: "Intern",
      postedAgo: "5 day(s)",
      mode: "Remote"
    },
    {
      id: 4,
      title: "Marketing Executive",
      company: "MarketMinds",
      experience: "0 - 1 Years",
      salary: "2 - 3 LPA",
      type: "Full Time",
      location: "Chennai",
      skills: "Marketing, Branding, Sales",
      openToHire: "Fresher",
      postedAgo: "7 day(s)",
      mode: "In Office"
    },
    {
      id: 5,
      title: "Graphic Design Intern",
      company: "CreativeHive",
      experience: "0 Years",
      salary: "Stipend",
      type: "Internship",
      location: "Pune",
      skills: "Photoshop, Illustrator, Figma",
      openToHire: "Intern",
      postedAgo: "3 day(s)",
      mode: "Remote"
    },
    {
      id: 6,
      title: "HR Assistant (Fresher)",
      company: "PeoplePro",
      experience: "0 - 1 Years",
      salary: "2 - 3 LPA",
      type: "Full Time",
      location: "Hyderabad",
      skills: "Recruitment, Communication, HRMS",
      openToHire: "Fresher",
      postedAgo: "10 day(s)",
      mode: "In Office"
    },
    
  ];

